version: "2.0"
services:
  mysql:
    image: hypriot/rpi-mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ******
     
  phpmyadmin:
    depends_on:
      - mysql
    image: ebspace/armhf-phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ****** 
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - /home/pi/nginx/code:/code
        - /home/pi/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
  php:
    image: php:7-fpm
    volumes:
        - /home/pi/nginx/code:/code